### ISSUE TITLE
PATCH doesn't trigger Sequelize instance hooks

### ISSUE THREAD

**Issue by skinofstars** [feathersjs-ecosystem/feathers-sequelize#155]
_This refers to Sequelize hooks. Not Feathers hooks._

Doing a PATCH request doesn't trigger Sequelize inbuilt hooks, even when the service.options.raw is false.

The problem seems to be because we don't instance.update, rather we apply a Model.update
 
https://github.com/feathersjs-ecosystem/feathers-sequelize/blob/v3.1.0/lib/index.js#L219

This means the Sequelize hooks triggered are the bulk actions (afterBulkCreate/afterBulkUpdate) rather than the expected instance actions (afterCreate/afterUpdate).

**Comment by DesignByOnyx** [comment]
So, this has kind of been a recurring theme with PRs lately: people are creating multiple code paths to satisfy some edge conditions or micro-optimizations. This creates code that looks like this:

```js
if (someCondition) {
  doThingsOneWay();
} else {
  doThingsAnotherWay();
}
```

These extra code paths do not get tested by the shared adapter tests. This ends up affecting people who accidentally trigger one code path instead of the other without knowing - causing new and unexpected behaviors to "just appear one day".

My advise to you is to implement your code in both the "single" and "bulk" hooks. This should be very simple to do and will allow feathers-sequelize to continue to have a single code path for patches:

```js
function someCustomFunction (instance) {
  // do custom stuff here
  return Promise.resolve();
}
MyModel.hook('afterCreate', (instance, options) => {
  return someCustomFunction(instance);
});
MyModel.hook('afterBulkCreate', (instances, options) => {
  return Promise.all(instances.map(someCustomFunction));
});
```

**Comment by skinofstars** [comment]
I totally get that you want the code to be simple and stay out the way. The issue I've got with that is that it's acting unexpectedly. One would expect an action on a single record to perform an instance update, and a bulk action to trigger a bulk hook.

Worse still, these class hooks lose the instance context. So if the original service.Model has its schema set, this info is lost. That's all the more frustrating (impossible?) if you're chaining hooks.

**Comment by lijoantony** [comment]
It may not be possible to implement the same code in "bulk" hook instead of "single" variant, as they might not have access to the instance. For example `beforeUpdate(instance, options)` vs `beforeBulkUpdate(options)`.  Especially true when it's a library which got broken, when I switched from PUT to PATCH method.

**Comment by lijoantony** [comment]
@DesignByOnyx @skinofstars  Any advice to implement the functionality of `beforeUpdate` hook using `beforeBulkUpdate` since `beforeBulkUpdate` doesn't have instance param?

My project uses the library sequelize-paper-trail to implement some important features, which unfortunately got broken when I switched from PUT to PATCH method.

**Comment by skinofstars** [comment]
I don't think this should be closed. New users should be aware that the adapter will make Sequelize act differently to it's design and existing documentation.

**Comment by daffl** [comment]
Then we need some actionable steps and someone to implement them. I'm not even sure if that means a documentation or code update in this case.

**Comment by skinofstars** [comment]
Personally, I think it's a code change needed. It's not acting as expected and breaking core Sequelize functionality. 

We currently maintain our own monkey patched version of this module in order to be Sequelize compatible, but we're refactoring to just use Sequelize directly, which is what I would advise others to do.

**Comment by daffl** [comment]
Been talking to @alexisabril about a similar thing. Using Sequelize directly in a custom service is definitely starting to look like a more flexible, straightforward and viable approach going forward. Then this adapter could just provide some utility functions and default functionality but you are forced to use the Sequelize models directly.

This adapter with all its edge cases and special requirements is definitely one of the more painful Feathers modules to maintain at the moment.

**Comment by skinofstars** [comment]
If you aren't too far down the rabbit hole, then I'd recommend moving any event hooks out of Sequelize and in to the Feathers hooks system. It's easier to maintain and more apparent to the next dev looking at it.

**Comment by DaddyWarbucks** [comment]
> I second @skinofstars recommendation. If you're going to use sequelize, use it just as a query generator/executor. Don't bother with its hooks, eager data loading, or anything else - always favor using feathers hooks for all things business related... which includes data manipulation and validation, relational data loading ("eager" loading), caching, etc.

^^ This can be said with almost any adapter or tool integrated with Feathers. Favor feathers hooks over the built in methods/hooks. The only thing I disagree with here is the "relational data loading ("eager" loading)" **when querying/sorting**. You should use something like https://github.com/feathersjs-ecosystem/batch-loader for joining data onto the result. But, when you need to query/sort across tables, you should probably use `sequelize.include`.  This can be accomplished with hooks, for example https://daddywarbucks.github.io/feathers-fletching/hooks.html#joinquery. But there are loads of caveats compared to doing a true RDMS join.

I generally recommend a sequelize include that looks like this
```js
params.sequelize = {
  include: [
    model: MyModel,
    // empty array tells Sequelize not to actually "join" the result,
    // but still makes it available for querying/sorting. 
    attributes: []
  ]
}
```

You can also checkout https://daddywarbucks.github.io/feathers-fletching/hooks.html#sequelizejoinquery to help with join query/sort. I don't mean to plug my own libraries, but that is the hook I use to do what we are describing, which is to use Sequelize as little as possible.

@chrisbag I don't want to speak for Ryan (and he probably has a more eloquent answer), but I can give my opinion on what he means about Sequelize and Feathers having opposing goals. Sequelize favors models where Feathers favors services. I think it is best described in an example:

```js
// This is how you would fetch an author for a book in Sequelize. Sequelize stuffs all of its methods, hooks,
// helpers into its models. It's almost a monolithic structure. 
// Uh oh... does this method join on the author's PW?
book.getAuthor();

// In Feathers, we use the service for everything. The service replaces the model and the service
// interface is the only thing we should use to access the data. Doing so ensures all of our actions
// run through our app logic, such as protecting the author's PW
const author = await app.service('authors').get(book.author_id)
```

The goal of Sequelize is to be a robust ORM where all the config, logic, relationships, etc live in the ORM. Feathers breaks all of that out into services.

**Comment by DesignByOnyx** [comment]
I think Beau (DaddyWarbucks) captured my sentiments correctly. I should have probably specified "ORMs" in general as having an opposing agenda with feathers. It just happens that sequelize is the most "ORM-y" integration with feathers. ORMs provide a whole lot of complex functionality and API for managing data, but "the feathers way" would favor simple small bite-sized hooks for achieving the same functionality. When you drink the service-based koolaid for long enough (ala feathers), you start to really resent the difficulty and bloat of ORMs. 

The trap you fall into is when you try to use the ORM for all of it's "goodness" - I mean it's there, you should use it, right?You spend hours and hours trying to bend the ORM to your will. Then you finally get everything working correctly by turning the `raw` option on - thus disabling most of the features of the ARM. Then you begin to notice your DB queries getting slower and slower for no obvious reason. When you have no hair left on your head... some random thread on the internet makes you aware of this obscure option to keep queries fast (eg. `separate: true`). Then you go to investigate what that option is doing under the hood and you realize that the ORM switches modes to something which almost exactly matches the way feathers hooks work. At this point you have to buy a new computer because you threw your last one out the window, and you embrace the feathers way for all of it's amazingness.
