### ISSUE TITLE
count is slow on large data sets

### ISSUE THREAD

**Issue by jaslocum** [feathersjs-ecosystem/feathers-sequelize#178]
I created a fork and made the following change:

https://github.com/feathersjs-ecosystem/feathers-sequelize/commit/6be64f342fe9a1cb1d70c4fdc5f7db22767411f4

**Comment by DesignByOnyx** [comment]
The change you have suggested does not work as it only counts the results where as `findAndCount` counts ALL of the matching rows in the database. Let's say have 1000 rows in the database that match the query, but you are only selecting 20 rows at a time. Your solution would show "count: 20" instead of "count: 1000".

There have been suggestions in the past to use `find` whenever pagination is not being used - this will avoid an unnecessary count query. See issue #95. I recommend setting up indexing for your queries which are taking a long time, as this should solve your problem.

**Comment by jaslocum** [comment]
Thank you for your clarifying this. I have set my paginate option to false for all my production tables that are over 50K records.  However, I should be very careful about setting {paginate: false} in my production system because I could hang my backend if I return many thousands of records in one query.
