### ISSUE TITLE
Update / Insert Many-to-Many Relationship

### ISSUE THREAD

**Issue by daenuprobst** [feathersjs-ecosystem/feathers-sequelize#211]
I wonder what the correct way of dealing with many-to-many relationship is when I want to update a relationship. For example:

I have the table users and the table groups, as well as the table users_groups (standard 1:n m:1 stuff). Now, if I have an existing user and an existing group, and I want to add the user to the group.

So I'm aware of a couple of options:
- I just create a service for the table users_groups and insert the both ids into a new record there.
- I write a custom update method where I take care of it via the users or groups service.

What is the prefered way to do this, any suggestions?

Edit: Maybe to form this question as an actual issue. There should be documentation on how to do this, or rather, what the prefered way of doing it is.

**Comment by daenuprobst** [comment]
Yeah. I think it would be very interesting to have this working out of the box. My current approach is to use `{ raw: false }` so that my `FIND` and `GET` return a proper nested object. Keeping with my previous groups and users example, getting a user would return:

```javascript
{
    id: 6,
    firstName: 'John',
    lastName: 'Smith',
    groups: [
        { id: 9, name: 'The Avengers' },
        { id: 26, name: 'A-Team' }
    ]
}
```
 Of course, when I then update or patch the user, I have to add before hooks to `UPDATE` and `PATCH`, where I delete all associations from the table `users_groups` where `userId = 6` and then insert the new associations ([6, 9], [6, 26]). This definitively just feels wrong. Maybe there's a better way with only one query but I don't know enough about sequelize...

**Comment by daffl** [comment]
Having gone through it myself, I think that quite a bit of the challenges here are due to Sequelize's strange handling of many-to-many relationships. A model method like `addGroup` or `removeGroup` may look intuitive but how do you turn any user submitted data into the proper calls? This is probably a challenge for every web framework you are using Sequelize with - we just hear about it all the time because Feathers is one of the few that has a basic Sequelize adapter so people expect it to be solved.

For example, you can _create_ nested relationships automatically by [setting params.sequelize.include](https://github.com/feathersjs-ecosystem/feathers-sequelize#paramssequelize) but Sequelize does not let you create or update the list with _existing_ relationships (which I found super frustrating).

So - like you pointed out - you could create service representing the join table and modify it directly on the client. Or do what you did and delete and re-create the associations which is probably what people in most other frameworks end up doing as well.

**Comment by daenuprobst** [comment]
Would it make sense to include a generic hook (in addition to hydrate / dehydrate), which does the deletion and re-creation?

**Comment by musicformellons** [comment]
@daenuprobst I am also using {raw: false} but get something more like:
```
{
    id: 6,
    firstName: 'John',
    lastName: 'Smith',
    UserGroups: [
        { id: 9, group_id: 2 },
        { id: 26, group_id: 3 }
    ]
}
```
So how do you get your nice nested 'final' result?

**Comment by daffl** [comment]
You have to set the name (`as`) in your include options.

@daenuprobst I think that may make sense. Basically a hook that does what Sequelize doesn't which is:

- Go through each associated entry
- Check if it has an `id`
  - If it does check if it has the association
  - If not, add it
- If it doesn't, leave it

**Comment by abalad** [comment]
I have the same problem. Well I'm saving a model with a BeltToMany relationship. But I wanted the relationship to be created if it did not exist

**Comment by abalad** [comment]
Usuario Model:
```javascript
  usuario.associate = function (models) {
    usuario.belongsToMany(models.perfil, {
      through: 'usuario_perfil',
      foreignKey: 'usuario_id',
    });
  };
```
Perfil Model:
```javascript
  perfil.associate = function (models) {
    perfil.belongsToMany(models.usuario, {
      through: 'usuario_perfil',
      foreignKey: 'perfil_id',
    });
  };
```



Object to Save:
```json
{
	"nome": "Michael Jackson",
	"apelido": "Robert",
	"email": "example@example.com",
	"senha": "12345678",
	"usuario": "Anywhare",
	"perfils": [
	    {
	    	"id": "e4d03aa1-9735-4930-97af-53611a081d52",
		"descricao": "Access Manager"
	    },
	    {
	    	"id": "030408fa-d813-44a0-a399-5fe54e43e909",
		"descricao": "Medic"
	    }
    ]
}
```
