### ISSUE TITLE
Cannot use composite keys for CRUD operations

### ISSUE THREAD

**Issue by bernardobelchior** [feathersjs-ecosystem/feathers-sequelize#218]
### Steps to reproduce

1. Create a feathers service that uses a model with a composite key. 
1. Try to query a table with the composite key. There's no examples of this in the documentation, but from the [code](https://www.facebook.com/ilpizzaioloporto/app/128953167177144/) using an ID seems hardcoded.

### Expected behavior
Be able to query for a composite key, maybe using an array in the id parameter of the feathers services operations.

### Actual behavior
N/A

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
* feathers-sequelize: 3.1.2
* @feathersjs/feathers: 3.1.6

**NodeJS version**: v.9.10.1

**Operating System**: Arch Linux 4.17.2

**Browser Version**: Firefox Developer Edition 61.0b14 (64-bit)

**Module Loader**: None

**Comment by daffl** [comment]
We could make it possible to pass an array for the id but it will only work internally or via websockets because REST ids will always be strings (although you could always parse it and set the array as `context.id` in a `before` hook). If someone has an idea how to make https://github.com/feathersjs-ecosystem/feathers-sequelize/blob/master/lib/index.js#L102 work with it, I'm definitely open for pull requests.

**Comment by bernardobelchior** [comment]
Maybe add an `id` field to the `params` object that could handle that? 
If the id in the function arguments was set, it would use that, otherwise it would check for the `id` in `params`. What do you think?

**Comment by dekelev** [comment]
https://github.com/feathersjs-ecosystem/feathers-sequelize/pull/223

**Comment by DesignByOnyx** [comment]
This would be fairly tricky to implement and opens the door to weird bugs and support issues (eg. users must define their models correctly _and_ implement service calls correctly). I also think there's too much opinion about the routing for the to be built-in. For example, in the PR the OP suggests passing a serialized object as the id param - I assume something like this:

```
/some-service/{"foo": "bar", "bing": 1234}
```
... which looks like this once it's encoded (yuk):

```
/some-service/%7B%22foo%22:%20%22bar%22,%20%22bing%22:%201234%7D
```

The OP also suggests adding a special "id" prop to the params object, which just seems to have a code smell to me. Other's on Stack Overflow have [widely varying opinions](https://github.com/feathersjs-ecosystem/feathers-sequelize#testing-sequelize-queries-in-isolation).

In my experience composite IDs proved to be kind of an anti-pattern and it always caused more headache than it was worth. I found that the _"combination of fields which should always be unique"_ is more of a "business rule" and a constraint you can put on SQL tables while also having a separate identifier column - and this separate identifier _always_ made life easier, code was easier, et al (think about foreign keys and relationships).

Another way to look at this is, if you take a persons hair color, eye color, weight, height, and 20 other attributes about them, you can uniquely identify that person out of the 7 billion people on this planet. However, it's way easier to just issue them a passport - see what I'm saying? The same applies with almost any object - the ability to identify an object by a combination of attributes does not really qualify as an identifier, especially in terms of "primary key" semantics.

Due to the infrequency of this feature request, the complexity behind implementing it, and the opinion about routing... I think compound identifiers are the responsibility of users and not feathers.

**Comment by DesignByOnyx** [comment]
And when I say "primary key" semantics, what I mean is this:

In every project I have ever done I have a "users" table, users have an "email" column, and the "email" column must be unique. However, I never use "email" as an primary key because that's not what it is. A "primary key" to me is something that happens when a user is put into a table and that user row must be identified somehow. No matter what happens, the primary key will always point to that user row. While the email could be used to find that row, an "email" has a different meaning than a "primary key", so I don't conflate the two. The same could be said about social security numbers. These are all things which we think might never change - but indeed someone can change their email or be issued a new social security number. This data should be able to change while the primary key still points to the same row in the table.

This further cascades to routing. By definition, a URL is a unique identifier to a resource on the internet. If you have routing which looks like `/user/1234` where 1234 is a primary key, the user can change any of their information and "1234" will always point to that same user. If you have `/user/foo@bar.com` and they change their email, then URL no longer points to them.

**Comment by DesignByOnyx** [comment]
@makensonlamour - this feature is not likely to be implemented. Composite keys introduce too many headaches in terms of routing, foreign keys, etc. I would strongly advise you against using them. FWIW - I have 4 more years of experience since my explanations above... and I still stand by those explanations.

**Comment by charsi** [comment]
I agree with @DesignByOnyx that composite primary keys should not be used. A single key is much more convenient. Unfortunately I am developing against a db for a legacy app so db changes are difficult. 

This is my slightly hacky workaround to use a composite primary key - 

```ts
// drop this into a before hook.

const compositeQuery= async (context: HookContext) => {
  const [name,type,systemId,groupId] = (context.id as string).split(',');

  // force an internal find query to override the default get
  context.result = ((await app.service('bla').find(
    {
      query: {
        id: name,
        system_type: type,
        installation_id: systemId,
        group_id: groupId
      },
      paginate: false,
    })) as any[])[0];
  return context;
};
```
