### ISSUE TITLE
Sequelize V5

### ISSUE THREAD

**Issue by gerwintown** [feathersjs-ecosystem/feathers-sequelize#283]
Hey,

I see a Greenkeeper branch, but I can't seem to find any related issues or discussion about Sequelize V5.  Only reason I am asking is because now that Sequelize has upgraded, they are no longer hosting the V4 Reference docs, which is frustrating in itself, but for me is going to demand that I follow along with that.

So, wondering if anybody has looked into it, or if there is any sort of timeline, and also, if there is any way I could help.  Forgive me if this is a redundant question answered elsewhere, if so please point me in the right direction!

Thanks!

**Comment by Flet** [comment]
Hi!

I noticed this too. 

I just cloned this repo and tried bumping the `sequelize` dev dependencies and all tests passed. Thats a good sign!

I'm not sure if the tests cover all cases, but they do give 93% code coverage. Since its a dev dependency we should be able to just start using V5 without touching this repository.

So, I think it can be used, but its probably worth going through the [Sequelize upgrade to V5](http://docs.sequelizejs.com/manual/upgrade-to-v5.html) docs and validating the breaking changes.

**Comment by daffl** [comment]
Yes, the base tests are looking good so upgrading should be possible. This adapter does not directly depend on Sequelize so all you should have to do is upgrade the version of the Sequelize dependency in your application.

I noticed the upgrade is breaking one of our applications but I didn't have a chance yet to figure out if it is something in this adapter or one of the breaking changes in Sequelize itself.

**Comment by daffl** [comment]
Closed via https://github.com/feathersjs-ecosystem/feathers-sequelize/pull/281 and released as v5.0.0. It probably didn't require a major release but it fit to have it be the same major version as Sequelize.
