### ISSUE TITLE
Underscored foreignKeys failing when upgrading to v5

### ISSUE THREAD

**Issue by fabls** [feathersjs-ecosystem/feathers-sequelize#287]
### Steps to reproduce

Writing to an underscored foreignKey field fails with `Model.options.underscored` enabled, see the following simplified example:

Model association definition:
`chat.belongsTo(chat, {as: 'parent_chat'});`

Sample Query:
app.service('chat').create({parent_chat_id: 1});

### Expected behavior
In the database the field `parent_chat_id` should be created and the query should create a database entry with `parent_chat_id` set to 1.

### Actual behavior
In the database the field `parent_chat_id` is created, but the query fails to write the `parent_chat_id` (NULL instead of 1).

This was working with sequelize/feathers-sequelize v4, but broke with v5. As a workaround the model definition can be changed as follows
`chat.belongsTo(chat, {as: 'parent_chat', foreignKey: 'parent_chat_id' });`
or the query can be changed to `app.service('chat').create({parentChatId: 1});`

**Comment by daffl** [comment]
This is probably an [issue for Sequelize](https://github.com/sequelize/sequelize) since this adapter is not doing anything with the model definition.

**Comment by Mairu** [comment]
If you use the underscore: true option you have to define the foreignKey options without underscore.

`chat.belongsTo(chat, {as: 'parentChat', foreignKey: 'parentChatId' });` with underscore option this will use a database field parent_chat_id.

If you want to use underscore separated names in database and models, set the underscore option to false, so that no transformation is done. See http://docs.sequelizejs.com/manual/upgrade-to-v5.html and https://github.com/sequelize/sequelize/issues/6423#issuecomment-379472035

This is not an issue of feathers-sequelize and should therefor be closed.

**Comment by frastlin** [comment]
[Here is the respective issue reported to Sequelize](https://github.com/sequelize/sequelize/issues/11062)
