### ISSUE TITLE
Incorrect format of DataTypes.BIGINT.UNSIGNED fields into the produced json

### ISSUE THREAD

**Issue by ramsestom** [feathersjs-ecosystem/feathers-sequelize#341]
I have models with fields defined as DataTypes.BIGINT.UNSIGNED . But the json produced by feathers as answer to requests on these models/tables do not meet the standard json format as it put double quotes arround these numeric fields. As a consequence, these fields are interpreted as String/text fields by the various json parsers. Could you fix this issue and make this plugin to treat all numeric DataTypes (see https://codewithhugo.com/sequelize-data-types-a-practical-guide/ for all the possible types) as json numeric fields (currently only a part of all the possible numeric fields, like DataTypes.INTEGER, seems to be considered as such when output to json)

**Comment by daffl** [comment]
This is probably a Sequelize question since Feathers uses the same `.toJSON` mechanism as most other libraries. Feathers specific things to look into would be to [use raw: false](https://github.com/feathersjs-ecosystem/feathers-sequelize#sequelize-raw-queries) and using a [custom formatter](https://docs.feathersjs.com/api/express.html#app-configure-express-rest-formatter).
